normalize:
  uppercase: false
  strip_non_alnum: false
  collapse_delims: "-"
  left_pad_numbers: false
  pad_length: 6
  trim_whitespace: true

provisioning:
  strategy: "namespaced"
  auto_approve: false

simulation:
  seed: 42
  scenario: "normal"
